# Generated by Django 5.2.7 on 2025-10-29 04:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('role', models.CharField(choices=[('1', '相談者'), ('2', '占い師'), ('3', '管理者')], max_length=1)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FortunetellerProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='fortune_pro', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=20)),
                ('headline', models.CharField(max_length=30)),
                ('intro', models.TextField(max_length=1000)),
                ('rank', models.CharField(choices=[('SILVER', 'シルバー'), ('GOLD', 'ゴールド'), ('PLATINUM', 'プラチナ')], default='SILVER', max_length=8)),
                ('profile_image', models.ImageField(upload_to='profile_images/')),
                ('icon_image', models.ImageField(upload_to='icon_images/')),
                ('is_recommended', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuerentProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='querent_pro', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=20)),
                ('tel_number', models.CharField(max_length=11)),
                ('postal_code', models.CharField(max_length=7)),
                ('address', models.CharField(max_length=255)),
                ('birthdate', models.DateField()),
                ('zodiac_sign', models.CharField(choices=[('牡羊座', '牡羊座'), ('牡牛座', '牡牛座'), ('双子座', '双子座'), ('蟹座', '蟹座'), ('獅子座', '獅子座'), ('乙女座', '乙女座'), ('天秤座', '天秤座'), ('蠍座', '蠍座'), ('射手座', '射手座'), ('山羊座', '山羊座'), ('水瓶座', '水瓶座'), ('魚座', '魚座')], max_length=3)),
                ('birthplace', models.CharField(max_length=50)),
                ('birthtime', models.TimeField()),
                ('worry_category', models.CharField(choices=[('恋愛', '恋愛'), ('仕事', '仕事'), ('人間関係', '人間関係'), ('金運', '金運'), ('健康', '健康')], max_length=4)),
                ('worry_message', models.TextField(max_length=1000)),
                ('is_subscription', models.BooleanField(default=False)),
                ('points', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BankInfo',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='fortune_pro', serialize=False, to='api.fortunetellerprofile')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('branch_name', models.CharField(blank=True, max_length=20, null=True)),
                ('account_type', models.CharField(blank=True, choices=[('普通', '普通'), ('法人', '法人'), ('当座', '当座'), ('貯蓄', '貯蓄')], max_length=2, null=True)),
                ('account_number', models.CharField(blank=True, max_length=7, null=True)),
                ('acount_holder_name', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
