# Generated by Django 5.2.7 on 2025-10-29 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankinfo',
            old_name='acount_holder_name',
            new_name='account_holder_name',
        ),
    ]
