# Generated by Django 5.2.7 on 2025-10-30 01:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_acount_holder_name_bankinfo_account_holder_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fortuneteller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_for', to='api.fortunetellerprofile')),
                ('querent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_que', to='api.querentprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('fortuneteller', '占い師'), ('querent', '相談者')], max_length=13)),
                ('text', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='message_files/')),
                ('cost_pt', models.IntegerField(blank=True, max_length=5, null=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room', to='api.room')),
            ],
        ),
    ]
